#!/bin/sh

#选择的菜单
menu_choice=""
current_cd=""
title_file="title.cdb"
tracks_file="tracks.cdb"
				#临时文件
temp_file=/tmp/cdb.$$
				#设置Ctr+C中断组合
trap 'rm -f $temp_file' EXIT


get_return(){
	echo -e "Press return \c"
	read x
	return 0
}


#确定选择
get_confirm(){
	echo -e "Are you sure?\c"
	while true 
	do
	  read x
 	  case "$x" in
	  y | yes | Y | Yes | YES)
	    return 0;;
	  n | no | N | No | NO)
	    echo 
	    echo "Cancelled"
	    return 1;;
	  *) echo "please enter yes or no";;
	 esac
	 done
}

#菜单选择 保存choice变量
set_menu_choice(){
	clear
	echo "Options:-"
	echo 
	echo "	a) ADD new CD"
	echo "        f) Find CD "
	echo "	c) count the cds and tracks in the catalog"
	if [ "$cdcatnum" != "" ]; then
	   echo "	 l) List tracks on $cdtitle"
	   echo "	 r) Remove $cdtitle"
	   echo "	 u) Update track information for $cdtitle"
	fi
	echo "	q) Quit"
	echo
	echo -e "Pleasse enter choice then press return \c"
	#保存选择的操作
	read menu_choice
	return
}


#插入标题
insert_title(){
	echo $* >> $title_file
}
#插入曲目
insert_track(){
	echo $* >> $tracks_file
}

#添加唱片曲目
add_record_tracks(){
	echo "Enter track informaiton for this CD"
	echo "When no more tracks enter q"
	cdtrack=1
	cdttitle=""
	while [ "$cdttitle" != "q" ]
	do 
	    echo -e "Trak $cdtrack,track title? \c"
	    read tmp 
	    cdttitle=${tmp%%,*}
	    if [ "$tmp" != "$cdttitle" ]; then
		echo "Sorry,no commas allowed"
		continue
	    fi

	    if [ -n "$cdttitle" ] ;then
		if [ "$cdttitle" != "q" ];then
		    insert_track $cdcatnum,$cdtarck,$cdttitle
		fi
	     else
		cdtrack=$((cdtrack-1))
	     fi
	    cdtrack=$((cdtrack+1))
	  done
}


add_records(){

    echo -e "Enter catalog name \c"
    read tmp 
    cdcatnum=${tmp%%,*}

    echo -e "Enter title \c"
    read tmp
    cdtitle=${tem%%,*}
    
    echo -e "Enter trye \c"
    read tmp
    cdtype=${tem%%,*}

    echo -e "Enter trye \c"
    read tmp
    cdac=${tem%%,*}

    echo About to add new entry
    echo "$cdcatnum $cdtitle $cdtype $cdac"

    if get_confirm ;then
	insert_title $cdcatnum,$cdtitle,$cdtype,$cdfile
	add_record_tracks
    else
	remove_records
    fi

return
    
}

find_cd(){
    if [ "$1" = "n" ];then
	asklist=n
    else 
	asklist=y
    fi
    cdcatnum=""
    echo -e "Enter a string to search for in the cd titles \c"
    read searchstr
    if [ "$searchstr" = "" ];then
	return 0
    fi
    
    grep "$searchstr" $title_file > $temp_file

    set $(wc -l $temp_file)
    linesfound=$1
    
    case "$linesfound" in 
	0) echo "sorry, nothing found"
	   get_return
	   return 0
	   ;;
	1) ;;
	2) echo "sorry,not unique."
	   echo "Found the following"
	   cat $temp_file
	   get_return
	   return 0
    esac

    IFS=","
    read cdcatnum cdtitle cdtype cdac <$temp_file
    IFS=" "

    if [ -z "$cdcatnum" ];then
	echo "Sorry ,could not extract catalog filed from $temp_file"
	get_return
	return 0
    fi
    echo
    echo Catalog number: $cdcatnum
    echo Title: $cdtitle
    echo Type:$cdtype
    echo Artist/Composer: $cdac
    echo 
    get_return

    if [ "$asklist" = "y" ];then
	echo -e "view tracks for this Cd?\c"
        read x
	if [ "$x" = "y" ];then 
	    echo
	    list_tracks
	    echo
	 fi
	fi
    return 1
}

update_cd(){
    if [ -z "$cdcatnum" ];then
	echo "You must select a cd first"
	filnd_cd n
    fi
    if [ -n "$cdcatnum" ];then
	echo "Current tracks are :-"
	list_tracks
	echo 
	echo "this will re-enter the tracks for $cdtitle"
	get_confirm && {
	    grep -v "^${cdcatnum}," $tracks_file > $temp_file
	    mv $temp_file $tracks_file
	    ehco
	    add_record_tracks

	}
	fi
    return
}

count_cds(){

    set $(wc -l $title_file)
    num_titles=$1
    set $(wc -l $tracks_file)
    num_tracks=$1
    echo foun $sum_titles CDs,with a total of &num_tracks tracks
    get_return
    return
}

remove_records(){
    if [ -z "$cdcatnum" ];then
	echo you must select a cd first
	find_cd n
    fi
    if [ -n "$cdcatnum" ] ;then
	echo "you ar about to delet $cdtitle"
	get_confirm && {
	    grep -v "^${cdcatnum}," $title_file > $temp_file
	    mv $temp_file $title_file
	    grep -v "^${cdcatnum}," $tracks_file >$temp_file
	    mv $temp_file $tracks_file
	    cdcatnum=""
	    echo Enter removed
	    }
	get_return
	fi
    return
}

list_tracks(){
    if [ "$cdcatnum" = "" ]; then
	echo no cd selected yet
	return
    else
	grep "^${cdcatnum}," $tracks_file > $temp_file
	num_tracks=$(wc -l $temp_file)
	if [ "$num_tracks" = "0" ];then
	    echo no tracks found for $cdtitle
	else {
		echo 
		echo "$cdtitle :-"
		echo 
		cut -f 2- -d , $temp_file
		echo
	    } | ${PAGER:-more}
	 fi
	fi
	get_return
	return
}


#删除临时文件
rm -f $temp_file
if [ ! f $title_file ];then
    touch $title_file
fi
if [ ! f $tracks_file ];then
    touch $tracks_file
fi

clear
echo
echo
echo "Min CD manger"
sleep 1

#接收输入
quit=n

while [ "$quit" != "y" ];
do
    #调用选择框
    set_menu_choice
    #比较接收的输入
    case "$menu_choice" in
	a) add_records;;
	r) remove_records;;
	f) find_cd y;;
	u) update_cd;;
	c) count_cds;;
	l) list_tracks;;
	b)
	    echo 
	    more $title_file
	    echo
	    get_return;;
	q | Q ) quit=y;;
	*) echo "Sorry,choice not recognized";;
    esac
 done

rm -f $temp_file
echo "Finished"
exit 0






